name: flutter_object_map
description: >-
  2-dimensional maps of objects linked by a [Key] and sub-type with
  explicitly typed methods to add, remove, and update the map.
version: 1.0.0
homepage: https://github.com/james-alex/object_map

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  object_map: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.1
